Reformat JSON to fix bug
Appended commas to the end of line 38 and 39 to properly complete the JSON. The lack of commas caused a malformed JSON exception in GSON. See below stack trace.

com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 39 column 3 path $..0.11.0
        at com.google.gson.Gson.fromJson(Gson.java:902) ~[server-1.15.2-extra.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:852) ~[server-1.15.2-extra.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:801) ~[server-1.15.2-extra.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:773) ~[server-1.15.2-extra.jar:?]
        at net.minecraftforge.fml.VersionChecker$1.process(VersionChecker.java:214) ~[?:?]
        at java.lang.Iterable.forEach(Iterable.java:75) [?:1.8.0_275]
        at net.minecraftforge.fml.VersionChecker$1.run(VersionChecker.java:157) [?:?]
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 39 column 3 path $..0.11.0
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559) ~[server-1.15.2-extra.jar:?]
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:491) ~[server-1.15.2-extra.jar:?]
        at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414) ~[server-1.15.2-extra.jar:?]
        at com.google.gson.internal.bind.ObjectTypeAdapter.read(ObjectTypeAdapter.java:69) ~[server-1.15.2-extra.jar:?]
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[server-1.15.2-extra.jar:?]
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187) ~[server-1.15.2-extra.jar:?]
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[server-1.15.2-extra.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:887) ~[server-1.15.2-extra.jar:?]
        ... 6 more